language: node_js
node_js:
  - 8
env:
  - NODE_ENV=production
cache:
  directories:
    - ".cache"
  yarn: true

install:
  - yarn

script:
  - yarn run build
  - echo "giuem.com" > ./dist/CNAME
  - chmod +x ./deploy.sh
  - ./deploy.sh > /dev/null
